= Practica:

Para poder realizar las configuraciones deberá ingresar en una sesión screen, una vez dentro de la sesión inicie las actividades.

Para realizar el login de screen ejecute lo siguiente en su terminal.
----
#screen -x examen
----

== Setup.

* Configure el servicio ssh para permitir el login remoto.

Configure el equipo con los siguiente valores.

* Parámetros de Red.
----
Interfaz eth1
Ip   192.168.122.10
Mask 255.255.255.0
----

* Nombre estético (alto nivel) :
----
"Equipo de evaluacion"
---- 
* Nombre estático:

----
"rhel-<username>.test.com"
----

* Nombre de ícono:
----
"computer"
---- 
* Zona Horaria
----
"America/Mexico_City"
----
* NTP Deshabilitado.


== Usuarios, Grupos y Contraseñas.

*Cambiar el password de root por 
----
"r3dh4t1!"
----
*Crear el usuario y asignar el password: 
----
"redhat" "redhat"
----

* El usuario "redhat deberá tener como grupo primario "extra"

* Crear el usuario "demo" con UID "2000" con password "changeme",  deberá forzar a que se actualice la contraseña en el próximo inicio de sesión.

* Crear el grupo    "extra"  con GUI "2500"

* Cambie el path del home de "demo2" a /home/<username>

* Mediante la escalación/elevación de privilegios como usuario "redhat" copie el directorio "etc" de manera re-cursiva en "mnt" 

== Redirecciones.

Dentro del directorio de archivo de dispositivos realice lo siguiente.

*  Redireccione la lista de todos los archivos especiales de bloque hacia el archivo block-dev.txt dentro del home del usuario demo2.
como usuario redhat

* Dentro de home crear los archivos a-file{1..3}

* Liste con la opción "-l" todos los archivos "a*" y "b*", mediante redirecciones envíe stdout a stdout.txt y los stderror a stderror.txt (ejecute todo en una sola línea).

* Liste con la opción "-l" todos los archivos "a*" y "b*", mediante redirecciones envíe stdout y stderror al mismo archivo "stdall.txt" (ejecute todo en una sola línea).

== Permisos:
* Crear el directorio apps en raíz.

* El directorio apps deberá pertenecer al usuario root.

* El directorio apps deberá pertenecer al grupo escritura.

* El usuario debe poder escribir dentro del directorio apps.

* Todos los archivos y subdirectorios creados en apps deberán pertenecer por defecto al grupo escritura. 
